name: '${project.name}'
version: '${project.version}'
author: Fabsi
api-version: '1.21'
main: me.fabsi.betterhappyghast.BetterHappyGhast
commands:
  betterhappyghastreload:
    usage: /<command>
    description: Reloads the configuration file
    permission: betterhappyghast.reload